# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "terraform-tfstate-hsulimann"
    key    = "eks-cluster/tf_eks_cluster/eks.tfstate"
    region = "us-east-1"
  }
}
