apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
    app: web
  ports:
    - name: httpd
      port: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      name: httpd
      labels:
        app: web
        tier: frontend
    spec:
      containers:
        - name: httpd
          image: 132818155912.dkr.ecr.us-east-1.amazonaws.com/terradorm-multi-cloud-repository:latest

